# Generated by Django 4.2.2 on 2023-06-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerceapp', '0003_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
